pumukit_cmar_web_tv_opencast_css:
    pattern: /opencast.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitCmarWebTVBundle::opencast.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css

pumukit_cmar_web_tv_series_css:
    pattern: /series.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitCmarWebTVBundle::series.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css

pumukit_cmar_web_tv_style_css:
    pattern: /style.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitCmarWebTVBundle::style.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css